server:
  port: 8081

spring:
  application:
    name: AUTH-SERVICE

  config:
    import: "optional:configserver:"

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: false

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: ${EUREKA_URL}

resend:
  api-key: ${RESEND_API_KEY}
  from-email: ${RESEND_FROM_EMAIL}

google:
  client-id: ${GOOGLE_CLIENT_ID}

management:
  endpoints:
    web:
      exposure:
        include: "*"

user:
  service:
    url: http://USER-SERVICE