version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: newsadmin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7

    container_name: redis

    restart: unless-stopped

    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1

    container_name: zookeeper

    restart: unless-stopped

    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1

    container_name: kafka

    restart: unless-stopped

    depends_on:
      - zookeeper

    ports:
      - "9092:9092"

    environment:
      KAFKA_BROKER_ID: 1

      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  service-registry:
    build:
      context: ./JAVA MICROSERVICES/SERVICE-REGISTRY

    container_name: service-registry

    restart: unless-stopped

    environment:
      SPRING_PROFILES_ACTIVE: docker

    ports:
      - "8761:8761"

    depends_on:
      - postgres
      - kafka

    networks:
      - default
      - squeezefeed-network

  api-gateway:
    build:
      context: ./JAVA MICROSERVICES/API-GATEWAY

    container_name: api-gateway

    restart: unless-stopped

    environment:
      SPRING_PROFILES_ACTIVE: docker

    ports:
      - "8080:8080"

    depends_on:
      - service-registry

    networks:
      - default
      - squeezefeed-network


  auth-service:
    build:
      context: ./JAVA MICROSERVICES/AUTH-SERVICE

    container_name: auth-service

    restart: unless-stopped

    environment:
      SPRING_PROFILES_ACTIVE: docker
      RESEND_API_KEY: ${RESEND_API_KEY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}

    ports:
      - "8081:8081"

    depends_on:
      - service-registry
      - postgres
      - kafka

    networks:
      - default
      - squeezefeed-network


  user-service:
    build:
      context: ./JAVA MICROSERVICES/USER-SERVICE

    container_name: user-service

    restart: unless-stopped

    environment:
      SPRING_PROFILES_ACTIVE: docker

    ports:
      - "8082:8082"

    depends_on:
      - service-registry
      - postgres
      - kafka

    networks:
      - default
      - squeezefeed-network

  content-service:
    build:
      context: ./JAVA MICROSERVICES/CONTENT-SERVICE

    container_name: content-service

    restart: unless-stopped

    environment:
      SPRING_PROFILES_ACTIVE: docker

    ports:
      - "8083:8083"

    depends_on:
      - service-registry
      - postgres
      - kafka

    networks:
      - default
      - squeezefeed-network


  news-orchestration-service:
    build:
      context: ./JAVA MICROSERVICES/NEWS-ORCHESTRATION-SERVICE

    container_name: news-orchestration-service

    restart: unless-stopped

    environment:
      SPRING_PROFILES_ACTIVE: docker

    ports:
      - "8084:8084"

    depends_on:
      - service-registry
      - postgres
      - kafka

    networks:
      - default
      - squeezefeed-network


  admin-service:
    build:
      context: ./JAVA MICROSERVICES/ADMIN-SERVICE

    container_name: admin-service

    restart: unless-stopped

    environment:
      SPRING_PROFILES_ACTIVE: docker

    ports:
      - "8085:8085"

    depends_on:
      - service-registry
      - postgres
      - kafka

    networks:
      - default
      - squeezefeed-network


  analytics-service:
    build:
      context: ./JAVA MICROSERVICES/ANALYTICS-SERVICE

    container_name: analytics-service

    restart: unless-stopped

    environment:
      SPRING_PROFILES_ACTIVE: docker

    ports:
      - "8086:8086"

    depends_on:
      - service-registry
      - postgres
      - kafka

    networks:
      - default
      - squeezefeed-network


  notification-service:
    build:
      context: ./JAVA MICROSERVICES/NOTIFICATION-SERVICE

    container_name: notification-service

    restart: unless-stopped

    environment:
      SPRING_PROFILES_ACTIVE: docker

    ports:
      - "8087:8087"

    depends_on:
      - service-registry
      - postgres
      - kafka

    networks:
      - default
      - squeezefeed-network


  media-service:
    build:
      context: ./JAVA MICROSERVICES/MEDIA-SERVICE

    container_name: media-service

    restart: unless-stopped

    environment:
      SPRING_PROFILES_ACTIVE: docker

    ports:
      - "8089:8089"

    depends_on:
      - service-registry
      - postgres
      - kafka

    networks:
      - default
      - squeezefeed-network

  scraper-service:
    build:
      context: ./PYTHON MICROSERVICES/scraper-service

    container_name: scraper-service

    restart: unless-stopped

    ports:
      - "8001:8001"

    depends_on:
      - redis

    networks:
      - default
      - squeezefeed-network


  sentiment-service:
    build:
      context: ./PYTHON MICROSERVICES/sentiment-service

    container_name: sentiment-service

    restart: unless-stopped

    ports:
      - "8002:8002"

    depends_on:
      - redis

    networks:
      - default
      - squeezefeed-network


  humanization-service:
    build:
      context: ./PYTHON MICROSERVICES/humanization-service

    container_name: humanization-service

    restart: unless-stopped

    ports:
      - "8003:8003"

    depends_on:
      - redis

    networks:
      - default
      - squeezefeed-network


  celery-worker:
    build:
      context: ./PYTHON MICROSERVICES/scraper-service

    container_name: celery-worker

    restart: unless-stopped

    command: celery -A app.workers.celery_worker.celery_app worker --pool=solo --loglevel=info

    depends_on:
      - redis

    networks:
      - default
      - squeezefeed-network


  celery-beat:
    build:
      context: ./PYTHON MICROSERVICES/scraper-service

    container_name: celery-beat

    restart: unless-stopped

    command: celery -A app.workers.celery_worker.celery_app beat --loglevel=info

    depends_on:
      - redis

    networks:
      - default
      - squeezefeed-network


volumes:
  postgres_data:

networks:
  squeezefeed-network:
    external: true