version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: newsadmin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7

    container_name: redis

    restart: unless-stopped

    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1

    container_name: zookeeper

    restart: unless-stopped

    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1

    container_name: kafka

    restart: unless-stopped

    depends_on:
      - zookeeper

    ports:
      - "9092:9092"

    environment:
      KAFKA_BROKER_ID: 1

      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  service-registry:
    build:
      context: ./JAVA MICROSERVICES/SERVICE-REGISTRY

    container_name: service-registry

    restart: unless-stopped

    environment:
      SPRING_PROFILES_ACTIVE: docker

    ports:
      - "8761:8761"

    depends_on:
      - postgres
      - kafka

    networks:
      - default
      - squeezefeed-network

  api-gateway:
    build:
      context: ./JAVA MICROSERVICES/API-GATEWAY

    container_name: api-gateway

    restart: unless-stopped

    environment:
      SPRING_PROFILES_ACTIVE: docker

    ports:
      - "8080:8080"

    depends_on:
      - service-registry

    networks:
      - default
      - squeezefeed-network


  auth-service:
    build:
      context: ./JAVA MICROSERVICES/AUTH-SERVICE

    container_name: auth-service

    restart: unless-stopped

    environment:
      SPRING_PROFILES_ACTIVE: docker

    ports:
      - "8081:8081"

    depends_on:
      - service-registry
      - postgres
      - kafka

    networks:
      - default
      - squeezefeed-network


volumes:
  postgres_data:

networks:
  squeezefeed-network:
    external: true