spring:

  config:
    import: "optional:configserver:http://config-server:8888"

  datasource:
    url: jdbc:postgresql://postgres:5432/news_media_db
    username: newsadmin
    password: root
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

media:
  upload-dir: /tmp/uploads/