server:
  port: 8080

spring:
  application:
    name: API-GATEWAY

  config:
    import: "optional:configserver:"

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      routes:

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**

        - id: content-service
          uri: lb://CONTENT-SERVICE
          predicates:
            - Path=/api/content/**

        - id: report-service
          uri: lb://CONTENT-SERVICE
          predicates:
            - Path=/api/reports/**

        - id: news-orchestration-service
          uri: lb://NEWS-ORCHESTRATION-SERVICE
          predicates:
            - Path=/api/orchestration/**

        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/api/admin/**

        - id: analytics-service
          uri: lb://ANALYTICS-SERVICE
          predicates:
            - Path=/api/analytics/**

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**

        - id: media-service
          uri: lb://MEDIA-SERVICE
          predicates:
            - Path=/api/media/**

eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: ${EUREKA_URL}

management:
  endpoints:
    web:
      exposure:
        include: "*"